\expandafter\ifx\csname graph\endcsname\relax \csname newbox\endcsname\graph\fi
\expandafter\ifx\csname graphtemp\endcsname\relax \csname newdimen\endcsname\graphtemp\fi
\setbox\graph=\vtop{\vskip 0pt\hbox{%
    \special{pn 8}%
    \special{ar 2618 294 706 294 0 6.28319}%
    \graphtemp=\baselineskip\multiply\graphtemp by -1\divide\graphtemp by 2
    \advance\graphtemp by .5ex\advance\graphtemp by 0.294in
    \rlap{\kern 2.618in\lower\graphtemp\hbox to 0pt{\hss option\hss}}%
    \graphtemp=\baselineskip\multiply\graphtemp by 1\divide\graphtemp by 2
    \advance\graphtemp by .5ex\advance\graphtemp by 0.294in
    \rlap{\kern 2.618in\lower\graphtemp\hbox to 0pt{\hss parsing\hss}}%
    \special{pa 1912 1676}%
    \special{pa 3324 1676}%
    \special{pa 3324 1088}%
    \special{pa 1912 1088}%
    \special{pa 1912 1676}%
    \special{fp}%
    \graphtemp=\baselineskip\multiply\graphtemp by -1\divide\graphtemp by 2
    \advance\graphtemp by .5ex\advance\graphtemp by 1.382in
    \rlap{\kern 2.618in\lower\graphtemp\hbox to 0pt{\hss all options\hss}}%
    \graphtemp=\baselineskip\multiply\graphtemp by 1\divide\graphtemp by 2
    \advance\graphtemp by .5ex\advance\graphtemp by 1.382in
    \rlap{\kern 2.618in\lower\graphtemp\hbox to 0pt{\hss passed to program\hss}}%
    \special{ar 2618 2471 706 294 0 6.28319}%
    \graphtemp=\baselineskip\multiply\graphtemp by -1\divide\graphtemp by 2
    \advance\graphtemp by .5ex\advance\graphtemp by 2.471in
    \rlap{\kern 2.618in\lower\graphtemp\hbox to 0pt{\hss loading\hss}}%
    \graphtemp=\baselineskip\multiply\graphtemp by 1\divide\graphtemp by 2
    \advance\graphtemp by .5ex\advance\graphtemp by 2.471in
    \rlap{\kern 2.618in\lower\graphtemp\hbox to 0pt{\hss input files\hss}}%
    \special{pa 1912 4206}%
    \special{pa 3324 4206}%
    \special{pa 3324 3265}%
    \special{pa 1912 3265}%
    \special{pa 1912 4206}%
    \special{fp}%
    \graphtemp=\baselineskip\multiply\graphtemp by -3\divide\graphtemp by 2
    \advance\graphtemp by .5ex\advance\graphtemp by 3.735in
    \rlap{\kern 2.618in\lower\graphtemp\hbox to 0pt{\hss input files:\hss}}%
    \graphtemp=\baselineskip\multiply\graphtemp by -1\divide\graphtemp by 2
    \advance\graphtemp by .5ex\advance\graphtemp by 3.735in
    \rlap{\kern 2.618in\lower\graphtemp\hbox to 0pt{\hss genomic sequence\hss}}%
    \graphtemp=\baselineskip\multiply\graphtemp by 1\divide\graphtemp by 2
    \advance\graphtemp by .5ex\advance\graphtemp by 3.735in
    \rlap{\kern 2.618in\lower\graphtemp\hbox to 0pt{\hss reference sequence\hss}}%
    \graphtemp=\baselineskip\multiply\graphtemp by 3\divide\graphtemp by 2
    \advance\graphtemp by .5ex\advance\graphtemp by 3.735in
    \rlap{\kern 2.618in\lower\graphtemp\hbox to 0pt{\hss splice site param.\hss}}%
    \special{ar 2618 5000 706 294 0 6.28319}%
    \graphtemp=\baselineskip\multiply\graphtemp by -1\divide\graphtemp by 2
    \advance\graphtemp by .5ex\advance\graphtemp by 5.000in
    \rlap{\kern 2.618in\lower\graphtemp\hbox to 0pt{\hss similarity\hss}}%
    \graphtemp=\baselineskip\multiply\graphtemp by 1\divide\graphtemp by 2
    \advance\graphtemp by .5ex\advance\graphtemp by 5.000in
    \rlap{\kern 2.618in\lower\graphtemp\hbox to 0pt{\hss filter\hss}}%
    \special{pa 1912 6382}%
    \special{pa 3324 6382}%
    \special{pa 3324 5794}%
    \special{pa 1912 5794}%
    \special{pa 1912 6382}%
    \special{fp}%
    \graphtemp=\baselineskip\multiply\graphtemp by -1\divide\graphtemp by 2
    \advance\graphtemp by .5ex\advance\graphtemp by 6.088in
    \rlap{\kern 2.618in\lower\graphtemp\hbox to 0pt{\hss List of\hss}}%
    \graphtemp=\baselineskip\multiply\graphtemp by 1\divide\graphtemp by 2
    \advance\graphtemp by .5ex\advance\graphtemp by 6.088in
    \rlap{\kern 2.618in\lower\graphtemp\hbox to 0pt{\hss Hits\hss}}%
    \special{pa 0 6382}%
    \special{pa 1412 6382}%
    \special{pa 1412 5794}%
    \special{pa 0 5794}%
    \special{pa 0 6382}%
    \special{fp}%
    \graphtemp=\baselineskip\multiply\graphtemp by -1\divide\graphtemp by 2
    \advance\graphtemp by .5ex\advance\graphtemp by 6.088in
    \rlap{\kern 0.706in\lower\graphtemp\hbox to 0pt{\hss DP\hss}}%
    \graphtemp=\baselineskip\multiply\graphtemp by 1\divide\graphtemp by 2
    \advance\graphtemp by .5ex\advance\graphtemp by 6.088in
    \rlap{\kern 0.706in\lower\graphtemp\hbox to 0pt{\hss parameter\hss}}%
    \special{ar 2618 7529 1059 441 0 6.28319}%
    \graphtemp=\baselineskip\multiply\graphtemp by -2\divide\graphtemp by 2
    \advance\graphtemp by .5ex\advance\graphtemp by 7.529in
    \rlap{\kern 2.618in\lower\graphtemp\hbox to 0pt{\hss DP algorithm\hss}}%
    \graphtemp=.5ex\advance\graphtemp by 7.529in
    \rlap{\kern 2.618in\lower\graphtemp\hbox to 0pt{\hss for optimal\hss}}%
    \graphtemp=\baselineskip\multiply\graphtemp by 2\divide\graphtemp by 2
    \advance\graphtemp by .5ex\advance\graphtemp by 7.529in
    \rlap{\kern 2.618in\lower\graphtemp\hbox to 0pt{\hss spliced alignment\hss}}%
    \special{pa 4176 7824}%
    \special{pa 5588 7824}%
    \special{pa 5588 7235}%
    \special{pa 4176 7235}%
    \special{pa 4176 7824}%
    \special{fp}%
    \graphtemp=\baselineskip\multiply\graphtemp by -1\divide\graphtemp by 2
    \advance\graphtemp by .5ex\advance\graphtemp by 7.529in
    \rlap{\kern 4.882in\lower\graphtemp\hbox to 0pt{\hss one spliced\hss}}%
    \graphtemp=\baselineskip\multiply\graphtemp by 1\divide\graphtemp by 2
    \advance\graphtemp by .5ex\advance\graphtemp by 7.529in
    \rlap{\kern 4.882in\lower\graphtemp\hbox to 0pt{\hss alignment\hss}}%
    \special{ar 4882 6294 1059 441 0 6.28319}%
    \graphtemp=\baselineskip\multiply\graphtemp by -1\divide\graphtemp by 2
    \advance\graphtemp by .5ex\advance\graphtemp by 6.294in
    \rlap{\kern 4.882in\lower\graphtemp\hbox to 0pt{\hss spliced alignment\hss}}%
    \graphtemp=\baselineskip\multiply\graphtemp by 1\divide\graphtemp by 2
    \advance\graphtemp by .5ex\advance\graphtemp by 6.294in
    \rlap{\kern 4.882in\lower\graphtemp\hbox to 0pt{\hss collection\hss}}%
    \special{pa 4176 5353}%
    \special{pa 5588 5353}%
    \special{pa 5588 4765}%
    \special{pa 4176 4765}%
    \special{pa 4176 5353}%
    \special{fp}%
    \graphtemp=\baselineskip\multiply\graphtemp by -2\divide\graphtemp by 2
    \advance\graphtemp by .5ex\advance\graphtemp by 5.059in
    \rlap{\kern 4.882in\lower\graphtemp\hbox to 0pt{\hss binary search tree\hss}}%
    \graphtemp=.5ex\advance\graphtemp by 5.059in
    \rlap{\kern 4.882in\lower\graphtemp\hbox to 0pt{\hss of spliced\hss}}%
    \graphtemp=\baselineskip\multiply\graphtemp by 2\divide\graphtemp by 2
    \advance\graphtemp by .5ex\advance\graphtemp by 5.059in
    \rlap{\kern 4.882in\lower\graphtemp\hbox to 0pt{\hss alignments\hss}}%
    \special{ar 4882 3971 706 294 0 6.28319}%
    \graphtemp=\baselineskip\multiply\graphtemp by -1\divide\graphtemp by 2
    \advance\graphtemp by .5ex\advance\graphtemp by 3.971in
    \rlap{\kern 4.882in\lower\graphtemp\hbox to 0pt{\hss output spliced\hss}}%
    \graphtemp=\baselineskip\multiply\graphtemp by 1\divide\graphtemp by 2
    \advance\graphtemp by .5ex\advance\graphtemp by 3.971in
    \rlap{\kern 4.882in\lower\graphtemp\hbox to 0pt{\hss alignments\hss}}%
    \special{pa 4176 3176}%
    \special{pa 5588 3176}%
    \special{pa 5588 2588}%
    \special{pa 4176 2588}%
    \special{pa 4176 3176}%
    \special{fp}%
    \graphtemp=\baselineskip\multiply\graphtemp by -2\divide\graphtemp by 2
    \advance\graphtemp by .5ex\advance\graphtemp by 2.882in
    \rlap{\kern 4.882in\lower\graphtemp\hbox to 0pt{\hss output\hss}}%
    \graphtemp=.5ex\advance\graphtemp by 2.882in
    \rlap{\kern 4.882in\lower\graphtemp\hbox to 0pt{\hss of spliced\hss}}%
    \graphtemp=\baselineskip\multiply\graphtemp by 2\divide\graphtemp by 2
    \advance\graphtemp by .5ex\advance\graphtemp by 2.882in
    \rlap{\kern 4.882in\lower\graphtemp\hbox to 0pt{\hss alignments\hss}}%
    \special{pa 3824 1676}%
    \special{pa 5235 1676}%
    \special{pa 5235 1088}%
    \special{pa 3824 1088}%
    \special{pa 3824 1676}%
    \special{fp}%
    \graphtemp=\baselineskip\multiply\graphtemp by -2\divide\graphtemp by 2
    \advance\graphtemp by .5ex\advance\graphtemp by 1.382in
    \rlap{\kern 4.529in\lower\graphtemp\hbox to 0pt{\hss BSSM\hss}}%
    \graphtemp=.5ex\advance\graphtemp by 1.382in
    \rlap{\kern 4.529in\lower\graphtemp\hbox to 0pt{\hss parameter\hss}}%
    \graphtemp=\baselineskip\multiply\graphtemp by 2\divide\graphtemp by 2
    \advance\graphtemp by .5ex\advance\graphtemp by 1.382in
    \rlap{\kern 4.529in\lower\graphtemp\hbox to 0pt{\hss files\hss}}%
    \special{ar 6441 1382 706 294 0 6.28319}%
    \graphtemp=.5ex\advance\graphtemp by 1.382in
    \rlap{\kern 6.441in\lower\graphtemp\hbox to 0pt{\hss mkbssmfiles.x\hss}}%
    \special{pa 0 2765}%
    \special{pa 1412 2765}%
    \special{pa 1412 2176}%
    \special{pa 0 2176}%
    \special{pa 0 2765}%
    \special{fp}%
    \graphtemp=\baselineskip\multiply\graphtemp by -2\divide\graphtemp by 2
    \advance\graphtemp by .5ex\advance\graphtemp by 2.471in
    \rlap{\kern 0.706in\lower\graphtemp\hbox to 0pt{\hss index of\hss}}%
    \graphtemp=.5ex\advance\graphtemp by 2.471in
    \rlap{\kern 0.706in\lower\graphtemp\hbox to 0pt{\hss genomic and\hss}}%
    \graphtemp=\baselineskip\multiply\graphtemp by 2\divide\graphtemp by 2
    \advance\graphtemp by .5ex\advance\graphtemp by 2.471in
    \rlap{\kern 0.706in\lower\graphtemp\hbox to 0pt{\hss reference sequence\hss}}%
    \special{ar 706 1382 706 294 0 6.28319}%
    \graphtemp=.5ex\advance\graphtemp by 1.382in
    \rlap{\kern 0.706in\lower\graphtemp\hbox to 0pt{\hss mkvtree.x\hss}}%
    \special{pa 2618 588}%
    \special{pa 2618 1088}%
    \special{fp}%
    \special{sh 1.000}%
    \special{pa 2643 988}%
    \special{pa 2618 1088}%
    \special{pa 2593 988}%
    \special{pa 2643 988}%
    \special{fp}%
    \special{pa 2618 1676}%
    \special{pa 2618 2176}%
    \special{fp}%
    \special{sh 1.000}%
    \special{pa 2643 2076}%
    \special{pa 2618 2176}%
    \special{pa 2593 2076}%
    \special{pa 2643 2076}%
    \special{fp}%
    \special{pa 2618 2765}%
    \special{pa 2618 3265}%
    \special{fp}%
    \special{sh 1.000}%
    \special{pa 2643 3165}%
    \special{pa 2618 3265}%
    \special{pa 2593 3165}%
    \special{pa 2643 3165}%
    \special{fp}%
    \special{pa 2618 4206}%
    \special{pa 2618 4706}%
    \special{fp}%
    \special{sh 1.000}%
    \special{pa 2643 4606}%
    \special{pa 2618 4706}%
    \special{pa 2593 4606}%
    \special{pa 2643 4606}%
    \special{fp}%
    \special{pa 2618 5294}%
    \special{pa 2618 5794}%
    \special{fp}%
    \special{sh 1.000}%
    \special{pa 2643 5694}%
    \special{pa 2618 5794}%
    \special{pa 2593 5694}%
    \special{pa 2643 5694}%
    \special{fp}%
    \special{pa 2618 5294}%
    \special{pa 706 5794}%
    \special{fp}%
    \special{sh 1.000}%
    \special{pa 809 5793}%
    \special{pa 706 5794}%
    \special{pa 796 5745}%
    \special{pa 809 5793}%
    \special{fp}%
    \special{pa 706 6382}%
    \special{pa 2618 7088}%
    \special{fp}%
    \special{sh 1.000}%
    \special{pa 2532 7030}%
    \special{pa 2618 7088}%
    \special{pa 2515 7077}%
    \special{pa 2532 7030}%
    \special{fp}%
    \special{pa 2618 6382}%
    \special{pa 2618 7088}%
    \special{fp}%
    \special{sh 1.000}%
    \special{pa 2643 6988}%
    \special{pa 2618 7088}%
    \special{pa 2593 6988}%
    \special{pa 2643 6988}%
    \special{fp}%
    \graphtemp=\baselineskip\multiply\graphtemp by -1\divide\graphtemp by 2
    \advance\graphtemp by .5ex\advance\graphtemp by 6.735in
    \rlap{\kern 2.618in\lower\graphtemp\hbox to 0pt{\hss for every\hss}}%
    \graphtemp=\baselineskip\multiply\graphtemp by 1\divide\graphtemp by 2
    \advance\graphtemp by .5ex\advance\graphtemp by 6.735in
    \rlap{\kern 2.618in\lower\graphtemp\hbox to 0pt{\hss hit\hss}}%
    \special{pa 3676 7529}%
    \special{pa 4176 7529}%
    \special{fp}%
    \special{sh 1.000}%
    \special{pa 4076 7504}%
    \special{pa 4176 7529}%
    \special{pa 4076 7554}%
    \special{pa 4076 7504}%
    \special{fp}%
    \special{pa 4882 7235}%
    \special{pa 4882 6735}%
    \special{da 0.050}%
    \special{sh 1.000}%
    \special{pa 4857 6835}%
    \special{pa 4882 6735}%
    \special{pa 4907 6835}%
    \special{pa 4857 6835}%
    \special{fp}%
    \graphtemp=.5ex\advance\graphtemp by 6.985in
    \rlap{\kern 4.882in\lower\graphtemp\hbox to 0pt{\hss possibly\hss}}%
    \special{pa 4882 5853}%
    \special{pa 4882 5353}%
    \special{fp}%
    \special{sh 1.000}%
    \special{pa 4857 5453}%
    \special{pa 4882 5353}%
    \special{pa 4907 5453}%
    \special{pa 4857 5453}%
    \special{fp}%
    \special{pa 4882 4765}%
    \special{pa 4882 4265}%
    \special{fp}%
    \special{sh 1.000}%
    \special{pa 4857 4365}%
    \special{pa 4882 4265}%
    \special{pa 4907 4365}%
    \special{pa 4857 4365}%
    \special{fp}%
    \special{pa 4882 3676}%
    \special{pa 4882 3176}%
    \special{fp}%
    \special{sh 1.000}%
    \special{pa 4857 3276}%
    \special{pa 4882 3176}%
    \special{pa 4907 3276}%
    \special{pa 4857 3276}%
    \special{fp}%
    \special{pa 4529 1676}%
    \special{pa 3324 2471}%
    \special{fp}%
    \special{sh 1.000}%
    \special{pa 3421 2436}%
    \special{pa 3324 2471}%
    \special{pa 3393 2395}%
    \special{pa 3421 2436}%
    \special{fp}%
    \special{pa 5735 1382}%
    \special{pa 5235 1382}%
    \special{fp}%
    \special{sh 1.000}%
    \special{pa 5335 1407}%
    \special{pa 5235 1382}%
    \special{pa 5335 1357}%
    \special{pa 5335 1407}%
    \special{fp}%
    \special{pa 1412 2471}%
    \special{pa 1912 2471}%
    \special{fp}%
    \special{sh 1.000}%
    \special{pa 1812 2446}%
    \special{pa 1912 2471}%
    \special{pa 1812 2496}%
    \special{pa 1812 2446}%
    \special{fp}%
    \special{pa 706 1676}%
    \special{pa 706 2176}%
    \special{fp}%
    \special{sh 1.000}%
    \special{pa 731 2076}%
    \special{pa 706 2176}%
    \special{pa 681 2076}%
    \special{pa 731 2076}%
    \special{fp}%
    \hbox{\vrule depth7.971in width0pt height 0pt}%
    \kern 7.147in
  }%
}%
